from utils import Colors, get_path, pos

WIDTH = 1200
HEIGHT = 650
DIMENSIONS = WIDTH, HEIGHT
SCREEN_COLOR = Colors.BLACK
TEXT_COLOR = Colors.BLUE
LARGER_FONT_SIZE = 115
LARGE_FONT_SIZE = 100
MEDIUM_FONT_SIZE = 40
SMALL_FONT_SIZE = 20
FPS = 30
GAME_NAME = 'Type Rush'
FONT = "Moon.otf"
FONT_PATH = get_path(__file__, FONT)
ICON = 'icon.ico'
ICON_PATH = get_path(__file__, ICON)
INITIAL_SPEED = .5
TEXT_SPEED = .001

BUTTON_WIDTH = WIDTH / 5
BUTTON_HEIGHT = HEIGHT / 10
BUTTON_SIZE = BUTTON_WIDTH, BUTTON_HEIGHT

LEFT_BUTTON_TEXT = 'Play!'
RIGHT_BUTTON_TEXT = 'Quit'
LEFT_BUTTON_COORDS = pos(WIDTH / 4, 5 * HEIGHT / 8)
RIGHT_BUTTON_COORDS = pos(3 * WIDTH / 4, 5 * HEIGHT / 8)
LEFT_BUTTON_COLORS = Colors.GREEN, Colors.BRIGHT_GREEN
RIGHT_BUTTON_COLORS = Colors.RED, Colors.BRIGHT_RED

del Colors
